package kg.santechmarket.enums;

/**
 * Коды ошибок для API
 */
public enum ErrorCode {
    // Authentication & Authorization
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED"),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID"),
    AUTH_REFRESH_TOKEN_EXPIRED("AUTH_REFRESH_TOKEN_EXPIRED"),
    AUTH_REFRESH_TOKEN_INVALID("AUTH_REFRESH_TOKEN_INVALID"),
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED"),
    AUTH_FORBIDDEN("AUTH_FORBIDDEN"),

    // User
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_INACTIVE("USER_INACTIVE"),
    USER_INVALID_PASSWORD("USER_INVALID_PASSWORD"),

    // Product
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
    PRODUCT_OUT_OF_STOCK("PRODUCT_OUT_OF_STOCK"),
    PRODUCT_INACTIVE("PRODUCT_INACTIVE"),

    // Category
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND"),

    // Cart
    CART_EMPTY("CART_EMPTY"),
    CART_ITEM_NOT_FOUND("CART_ITEM_NOT_FOUND"),
    CART_INVALID_QUANTITY("CART_INVALID_QUANTITY"),

    // Order
    ORDER_NOT_FOUND("ORDER_NOT_FOUND"),
    ORDER_INVALID_STATUS("ORDER_INVALID_STATUS"),
    ORDER_CANNOT_CANCEL("ORDER_CANNOT_CANCEL"),
    ORDER_ACCESS_DENIED("ORDER_ACCESS_DENIED"),

    // File Upload
    FILE_UPLOAD_FAILED("FILE_UPLOAD_FAILED"),
    FILE_DELETE_FAILED("FILE_DELETE_FAILED"),
    FILE_INVALID_TYPE("FILE_INVALID_TYPE"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),

    // Validation
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INVALID_REQUEST("INVALID_REQUEST"),

    // Server
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }
}
